"""initial migration: create core models

Revision ID: b55c55ba4959
Revises: 
Create Date: 2026-08-27 21:12:25.546433
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55c55ba4959'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('games_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('games_won', sa.Integer(), server_default='0', nullable=False),
    sa.Column('times_as_spy', sa.Integer(), server_default='0', nullable=False),
    sa.Column('times_spy_won', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_user_id', sa.BigInteger(), nullable=True),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('spies_count', sa.SmallInteger(), nullable=False),
    sa.Column('round_seconds', sa.Integer(), nullable=False),
    sa.Column('allow_two_spies', sa.Boolean(), nullable=False),
    sa.Column('winner', sa.Enum('CITIZENS', 'SPY', name='game_winner'), nullable=True),
    sa.Column('end_reason', sa.Enum('SPY_GUESSED_WORD', 'SPY_VOTED_OUT_WRONG_GUESS', 'SPY_VOTED_OUT_CORRECT_GUESS', 'CITIZEN_VOTED_OUT', 'CANCELLED', name='game_end_reason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.telegram_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_chat_id'), 'games', ['chat_id'], unique=False)
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'SPY', name='player_role'), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('votes_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('was_eliminated', sa.Boolean(), nullable=False),
    sa.Column('left_mid_game', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'user_id', name='uq_game_players_game_user')
    )
    op.create_index(op.f('ix_game_players_game_id'), 'game_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_players_user_id'), 'game_players', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_players_user_id'), table_name='game_players')
    op.drop_index(op.f('ix_game_players_game_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_index(op.f('ix_games_chat_id'), table_name='games')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
